### ISSUE TITLE
GFS Data not getting setting on Quote or Order

### ISSUE THREAD

**Issue by danielpavey** [GlobalFreightSolutions/magento2-gfs#1]
Hi

I am testing the magento2-gfs module on our Magento 2.3.1 test installation.

When placing test orders I can checkout successfully, however: 

gfs_checkout_result & gfs_session_id and not getting set on the quote table.

Subsequently gfs_checkout_result, gfs_close_checkout & gfs_session_id are not getting set on sales_order table.

However on both these tables gfs_shipping_data is getting set.

The customer admin screen then throws an error as it is trying to get gfs_close_checkout from the sales_order table. (https://github.com/GlobalFreightSolutions/magento2-gfs/blob/e6f3cf0c77fe5e53d429cfb1f067efbffe4f1841/Block/Adminhtml/Order/View/Info/Gfs.php#L122)

This admin info block calls the helper - https://github.com/GlobalFreightSolutions/magento2-gfs/blob/e6f3cf0c77fe5e53d429cfb1f067efbffe4f1841/Helper/Data.php#L47

Any idea why these database values are not getting set?

Thanks

**Comment by Simondwilson88** [comment]
Hi @danielpavey 

Thanks for reaching out to us.

The current iteration of the module is only compatible with Magento 2.2.5-2.2.7 in a stable version

Due to there being some core changes in Magento 2.3.X these have changed the way module interacts with Magento core and We are working on testing and supporting this into Magento 2.3.1.

If you would like me to keep you updated directly on this please reach out to me on our forums [located here](https://developer.gfsdeliver.com/forum)

I will ask the issue to be kept open and we will close this when a new files uploaded that resolve these issues.


Simon
Product Manager

**Comment by danielpavey** [comment]
Hi @Simondwilson88 

Thanks for the quick reply! 

I'll keep an eye on the forum and this repo.

Dan

**Comment by Simondwilson88** [comment]
@danielpavey Hi Daniel, we have updated the module to resolve this issue, the latest version is 1.1.2

please let me know if you have any other issues.

Best regards
Simon

**Comment by danielpavey** [comment]
Hi @Simondwilson88 

Thanks for letting me know. Will update ASAP!!

I've just noticed that your compose.json file still limits the php version to 7.1

Is there any reason for this?

Rgds

Dan
